
# Darrious Barger

# Problem:

# Each new term in the Fibonacci sequence is generated by adding
# the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose 
# values do not exceed four million, find the sum of the even-valued terms.

num1 = 1
num2 = 2
hold = num2
count = 2

sum = num2

while hold < 4_000_000:
	hold = num1 + num2
	num1 = num2
	num2 = hold

	count += 1
	if (hold < 4_000_000 and hold % 2 == 0):
		sum += hold
		print(count, hold)


print("\nSum:",sum)